#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#bindkey '\e[H' beginning-of-line
#bindkey '\e[F' end-of-line
#bindkey '^A' beginning-of-line
#bindkey '^E' end-of-line
bindkey '^P' history-search-backward
bindkey '^N' history-search-forward
bindkey "^L" backward-kill-line
bindkey "^u" down-case-word
bindkey "^[b" forward-word
bindkey '^[f' backward-word
bindkey '^f' history-incremental-search-backward


# Incremental search is elite!
bindkey -M vicmd "/" history-incremental-search-backward
bindkey -M vicmd "?" history-incremental-search-forward

#  # Search based on what you typed in already
bindkey -M vicmd "//" history-beginning-search-backward
bindkey -M vicmd "??" history-beginning-search-forward

unsetopt inc_append_history
unsetopt share_history


export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
export JAVA_HOME="$(/usr/libexec/java_home -v 11)"
alias cnpm="npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc"
alias k=kubectl
export PATH="/usr/local/opt/mysql-client/bin:$PATH"
export BUILD_LIBRDKAFKA=0
export GOPATH="$HOME/Projects/stupid_go"
export GOBIN="$GOPATH/bin"
export PATH="$PATH:$GOBIN"
source "$(navi widget zsh)"
export NAVI_PATH="$HOME/.cheats"
export GPG_TTY=$(tty)
